version: '2'
services:
  app:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - ast-tz-net

  db:
    image: mysql:8
    command: --mysql-native-password=ON
    container_name: ast-tz-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - /data/mysql-ast-tz:/var/lib/mysql
    networks:
      - ast-tz-net
    ports:
      - "3346:3306"

  testdb:
    image: mysql:8
    command: --mysql-native-password=ON
    container_name: ast-tz-testdb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME_TEST}
      MYSQL_ROOT_PASSWORD: ${DB_PASS_TEST}
      MYSQL_PASSWORD: ${DB_PASS_TEST}
      MYSQL_USER: ${DB_USER_TEST}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - /data/mysql-ast-tz-testdb:/var/lib/mysql
    networks:
      - ast-tz-net
    ports:
      - "3356:3306"

networks:
  ast-tz-net:
    driver: bridge